
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:05"
      timezone: "Europe/London"
registries:
  test_2:
    type: git
    url: https://github.com/ij-org/test_2
    username: x-access-token
    password: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}
